/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Types of notifications that can be sent to users
 */
export enum NotificationType {
    KYC_SUBMITTED = "KYC_SUBMITTED",
    KYC_APPROVED = "KYC_APPROVED",
    KYC_REJECTED = "KYC_REJECTED",
    WITHDRAWAL_APPROVED = "WITHDRAWAL_APPROVED",
    WITHDRAWAL_REJECTED = "WITHDRAWAL_REJECTED",
    DEPOSIT_CONFIRMED = "DEPOSIT_CONFIRMED",
    ROI_RECEIVED = "ROI_RECEIVED",
    COPY_TRADE_EXECUTED = "COPY_TRADE_EXECUTED",
    COPY_RELATIONSHIP_STARTED = "COPY_RELATIONSHIP_STARTED",
    COPY_RELATIONSHIP_PAUSED = "COPY_RELATIONSHIP_PAUSED",
    COPY_RELATIONSHIP_RESUMED = "COPY_RELATIONSHIP_RESUMED",
    COPY_RELATIONSHIP_STOPPED = "COPY_RELATIONSHIP_STOPPED",
    COMMISSION_CONFIRMED = "COMMISSION_CONFIRMED",
    INVESTMENT_MATURED = "INVESTMENT_MATURED",
    SECURITY_ALERT = "SECURITY_ALERT",
    SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
}
