/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComponentShowcaseRouteImport } from './routes/component-showcase'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardExecutionsRouteImport } from './routes/dashboard/executions'
import { Route as DashboardCopyTradingRouteImport } from './routes/dashboard/copy-trading'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTraderManagerRouteImport } from './routes/admin/trader-manager'
import { Route as AdminPlanManagerRouteImport } from './routes/admin/plan-manager'
import { Route as AdminLongTermRouteImport } from './routes/admin/long-term'
import { Route as AdminLedgerHistoryRouteImport } from './routes/admin/ledger-history'
import { Route as AdminKycReviewRouteImport } from './routes/admin/kyc-review'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBalanceAdjustmentRouteImport } from './routes/admin/balance-adjustment'
import { Route as AdminKycReviewUserIdRouteImport } from './routes/admin/kyc-review.$userId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentShowcaseRoute = ComponentShowcaseRouteImport.update({
  id: '/component-showcase',
  path: '/component-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExecutionsRoute = DashboardExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCopyTradingRoute = DashboardCopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTraderManagerRoute = AdminTraderManagerRouteImport.update({
  id: '/admin/trader-manager',
  path: '/admin/trader-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlanManagerRoute = AdminPlanManagerRouteImport.update({
  id: '/admin/plan-manager',
  path: '/admin/plan-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLongTermRoute = AdminLongTermRouteImport.update({
  id: '/admin/long-term',
  path: '/admin/long-term',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLedgerHistoryRoute = AdminLedgerHistoryRouteImport.update({
  id: '/admin/ledger-history',
  path: '/admin/ledger-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycReviewRoute = AdminKycReviewRouteImport.update({
  id: '/admin/kyc-review',
  path: '/admin/kyc-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBalanceAdjustmentRoute = AdminBalanceAdjustmentRouteImport.update({
  id: '/admin/balance-adjustment',
  path: '/admin/balance-adjustment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycReviewUserIdRoute = AdminKycReviewUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminKycReviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/component-showcase': typeof ComponentShowcaseRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/balance-adjustment': typeof AdminBalanceAdjustmentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/kyc-review': typeof AdminKycReviewRouteWithChildren
  '/admin/ledger-history': typeof AdminLedgerHistoryRoute
  '/admin/long-term': typeof AdminLongTermRoute
  '/admin/plan-manager': typeof AdminPlanManagerRoute
  '/admin/trader-manager': typeof AdminTraderManagerRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset': typeof AuthResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/copy-trading': typeof DashboardCopyTradingRoute
  '/dashboard/executions': typeof DashboardExecutionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/kyc-review/$userId': typeof AdminKycReviewUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/component-showcase': typeof ComponentShowcaseRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/balance-adjustment': typeof AdminBalanceAdjustmentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/kyc-review': typeof AdminKycReviewRouteWithChildren
  '/admin/ledger-history': typeof AdminLedgerHistoryRoute
  '/admin/long-term': typeof AdminLongTermRoute
  '/admin/plan-manager': typeof AdminPlanManagerRoute
  '/admin/trader-manager': typeof AdminTraderManagerRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset': typeof AuthResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/copy-trading': typeof DashboardCopyTradingRoute
  '/dashboard/executions': typeof DashboardExecutionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/kyc-review/$userId': typeof AdminKycReviewUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/component-showcase': typeof ComponentShowcaseRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/balance-adjustment': typeof AdminBalanceAdjustmentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/kyc-review': typeof AdminKycReviewRouteWithChildren
  '/admin/ledger-history': typeof AdminLedgerHistoryRoute
  '/admin/long-term': typeof AdminLongTermRoute
  '/admin/plan-manager': typeof AdminPlanManagerRoute
  '/admin/trader-manager': typeof AdminTraderManagerRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset': typeof AuthResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/copy-trading': typeof DashboardCopyTradingRoute
  '/dashboard/executions': typeof DashboardExecutionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/kyc-review/$userId': typeof AdminKycReviewUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/component-showcase'
    | '/dashboard'
    | '/home'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/plans'
    | '/privacy-policy'
    | '/signup'
    | '/support'
    | '/verify-email'
    | '/admin/balance-adjustment'
    | '/admin/dashboard'
    | '/admin/kyc-review'
    | '/admin/ledger-history'
    | '/admin/long-term'
    | '/admin/plan-manager'
    | '/admin/trader-manager'
    | '/admin/users'
    | '/auth/reset'
    | '/reset-password'
    | '/dashboard/account'
    | '/dashboard/copy-trading'
    | '/dashboard/executions'
    | '/dashboard/settings'
    | '/admin/kyc-review/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/component-showcase'
    | '/dashboard'
    | '/home'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/plans'
    | '/privacy-policy'
    | '/signup'
    | '/support'
    | '/verify-email'
    | '/admin/balance-adjustment'
    | '/admin/dashboard'
    | '/admin/kyc-review'
    | '/admin/ledger-history'
    | '/admin/long-term'
    | '/admin/plan-manager'
    | '/admin/trader-manager'
    | '/admin/users'
    | '/auth/reset'
    | '/reset-password'
    | '/dashboard/account'
    | '/dashboard/copy-trading'
    | '/dashboard/executions'
    | '/dashboard/settings'
    | '/admin/kyc-review/$userId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/component-showcase'
    | '/dashboard'
    | '/home'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/plans'
    | '/privacy-policy'
    | '/signup'
    | '/support'
    | '/verify-email'
    | '/admin/balance-adjustment'
    | '/admin/dashboard'
    | '/admin/kyc-review'
    | '/admin/ledger-history'
    | '/admin/long-term'
    | '/admin/plan-manager'
    | '/admin/trader-manager'
    | '/admin/users'
    | '/auth/reset'
    | '/reset-password'
    | '/dashboard/account'
    | '/dashboard/copy-trading'
    | '/dashboard/executions'
    | '/dashboard/settings'
    | '/admin/kyc-review/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ComponentShowcaseRoute: typeof ComponentShowcaseRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeRoute: typeof HomeRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlansRoute: typeof PlansRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminBalanceAdjustmentRoute: typeof AdminBalanceAdjustmentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminKycReviewRoute: typeof AdminKycReviewRouteWithChildren
  AdminLedgerHistoryRoute: typeof AdminLedgerHistoryRoute
  AdminLongTermRoute: typeof AdminLongTermRoute
  AdminPlanManagerRoute: typeof AdminPlanManagerRoute
  AdminTraderManagerRoute: typeof AdminTraderManagerRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthResetRoute: typeof AuthResetRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/component-showcase': {
      id: '/component-showcase'
      path: '/component-showcase'
      fullPath: '/component-showcase'
      preLoaderRoute: typeof ComponentShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/executions': {
      id: '/dashboard/executions'
      path: '/executions'
      fullPath: '/dashboard/executions'
      preLoaderRoute: typeof DashboardExecutionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/copy-trading': {
      id: '/dashboard/copy-trading'
      path: '/copy-trading'
      fullPath: '/dashboard/copy-trading'
      preLoaderRoute: typeof DashboardCopyTradingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trader-manager': {
      id: '/admin/trader-manager'
      path: '/admin/trader-manager'
      fullPath: '/admin/trader-manager'
      preLoaderRoute: typeof AdminTraderManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plan-manager': {
      id: '/admin/plan-manager'
      path: '/admin/plan-manager'
      fullPath: '/admin/plan-manager'
      preLoaderRoute: typeof AdminPlanManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/long-term': {
      id: '/admin/long-term'
      path: '/admin/long-term'
      fullPath: '/admin/long-term'
      preLoaderRoute: typeof AdminLongTermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ledger-history': {
      id: '/admin/ledger-history'
      path: '/admin/ledger-history'
      fullPath: '/admin/ledger-history'
      preLoaderRoute: typeof AdminLedgerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc-review': {
      id: '/admin/kyc-review'
      path: '/admin/kyc-review'
      fullPath: '/admin/kyc-review'
      preLoaderRoute: typeof AdminKycReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/balance-adjustment': {
      id: '/admin/balance-adjustment'
      path: '/admin/balance-adjustment'
      fullPath: '/admin/balance-adjustment'
      preLoaderRoute: typeof AdminBalanceAdjustmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc-review/$userId': {
      id: '/admin/kyc-review/$userId'
      path: '/$userId'
      fullPath: '/admin/kyc-review/$userId'
      preLoaderRoute: typeof AdminKycReviewUserIdRouteImport
      parentRoute: typeof AdminKycReviewRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardCopyTradingRoute: typeof DashboardCopyTradingRoute
  DashboardExecutionsRoute: typeof DashboardExecutionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardCopyTradingRoute: DashboardCopyTradingRoute,
  DashboardExecutionsRoute: DashboardExecutionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AdminKycReviewRouteChildren {
  AdminKycReviewUserIdRoute: typeof AdminKycReviewUserIdRoute
}

const AdminKycReviewRouteChildren: AdminKycReviewRouteChildren = {
  AdminKycReviewUserIdRoute: AdminKycReviewUserIdRoute,
}

const AdminKycReviewRouteWithChildren = AdminKycReviewRoute._addFileChildren(
  AdminKycReviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ComponentShowcaseRoute: ComponentShowcaseRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HomeRoute: HomeRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlansRoute: PlansRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminBalanceAdjustmentRoute: AdminBalanceAdjustmentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminKycReviewRoute: AdminKycReviewRouteWithChildren,
  AdminLedgerHistoryRoute: AdminLedgerHistoryRoute,
  AdminLongTermRoute: AdminLongTermRoute,
  AdminPlanManagerRoute: AdminPlanManagerRoute,
  AdminTraderManagerRoute: AdminTraderManagerRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthResetRoute: AuthResetRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
