"""add_wallet_copy_trading_balance_fields

Revision ID: 08481d0b5f27
Revises: ba9360c196d5
Create Date: 2025-09-29 15:48:31.679911

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '08481d0b5f27'
down_revision = 'ba9360c196d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_balance', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('copy_trading_balance', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('session_locked_until', sa.DateTime(), nullable=True))
    
    # Set default values for new columns
    op.execute("UPDATE \"user\" SET wallet_balance = balance, copy_trading_balance = 0.0, is_locked = false")
    
    # Make new columns NOT NULL after setting defaults
    op.alter_column('user', 'wallet_balance', nullable=False, server_default='0.0')
    op.alter_column('user', 'copy_trading_balance', nullable=False, server_default='0.0')
    op.alter_column('user', 'is_locked', nullable=False, server_default='false')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'session_locked_until')
    op.drop_column('user', 'is_locked')
    op.drop_column('user', 'copy_trading_balance')
    op.drop_column('user', 'wallet_balance')
    # ### end Alembic commands ###
