"""Add authentication support fields to User model

Revision ID: 1737235721
Revises: c26d4cf3918f
Create Date: 2025-09-18 19:28:41.835000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1737235721'
down_revision = 'c26d4cf3918f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add OAuth provider integration columns
    op.add_column('user', sa.Column('oauth_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('user', sa.Column('oauth_provider_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('oauth_account_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    
    # Add refresh token support columns
    op.add_column('user', sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    op.add_column('user', sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
    
    # Add authentication timestamps and security fields
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('account_locked_until', sa.DateTime(), nullable=True))
    
    # Create indexes for performance
    op.create_index(op.f('ix_user_oauth_provider_id'), 'user', ['oauth_provider_id'], unique=False)
    op.create_index(op.f('ix_user_refresh_token'), 'user', ['refresh_token'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index(op.f('ix_user_refresh_token'), table_name='user')
    op.drop_index(op.f('ix_user_oauth_provider_id'), table_name='user')
    
    # Drop authentication timestamps and security fields
    op.drop_column('user', 'account_locked_until')
    op.drop_column('user', 'failed_login_attempts')
    op.drop_column('user', 'last_login_at')
    
    # Drop refresh token support columns
    op.drop_column('user', 'refresh_token_expires_at')
    op.drop_column('user', 'refresh_token')
    
    # Drop OAuth provider integration columns
    op.drop_column('user', 'oauth_account_email')
    op.drop_column('user', 'oauth_provider_id')
    op.drop_column('user', 'oauth_provider')
    
    # ### end Alembic commands ###

