"""Add TradeSimulation and MarketDataCache models

Revision ID: 26ae61361ef8
Revises: b83cf1b7a582
Create Date: 2025-09-26 11:37:35.595188

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26ae61361ef8'
down_revision = 'b83cf1b7a582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketdatacache',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('daily_high', sa.Float(), nullable=True),
    sa.Column('daily_low', sa.Float(), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('tradesimulation',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('accountsummary_user_id_fkey', 'accountsummary', type_='foreignkey')
    op.create_foreign_key(None, 'accountsummary', 'user', ['user_id'], ['id'])
    op.drop_constraint('dailyperformance_user_id_fkey', 'dailyperformance', type_='foreignkey')
    op.create_foreign_key(None, 'dailyperformance', 'user', ['user_id'], ['id'])
    op.drop_constraint('trade_user_id_fkey', 'trade', type_='foreignkey')
    op.create_foreign_key(None, 'trade', 'user', ['user_id'], ['id'])
    op.alter_column('user', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index('ix_user_oauth_provider_id', table_name='user')
    op.drop_index('ix_user_refresh_token', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_refresh_token', 'user', ['refresh_token'], unique=False)
    op.create_index('ix_user_oauth_provider_id', 'user', ['oauth_provider_id'], unique=False)
    op.alter_column('user', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.create_foreign_key('trade_user_id_fkey', 'trade', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dailyperformance', type_='foreignkey')
    op.create_foreign_key('dailyperformance_user_id_fkey', 'dailyperformance', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'accountsummary', type_='foreignkey')
    op.create_foreign_key('accountsummary_user_id_fkey', 'accountsummary', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('tradesimulation')
    op.drop_table('marketdatacache')
    # ### end Alembic commands ###
