"""Add long_term_balance to user table

Revision ID: 3b650978d9ad
Revises: 108ffa5ad0a2
Create Date: 2025-10-05 15:25:27.956701

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b650978d9ad'
down_revision = '108ffa5ad0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levelrequirement',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('longtermplan',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tier', sa.Enum('FOUNDATION', 'GROWTH', 'ELITE', name='longtermplantier'), nullable=True),
    sa.Column('minimum_deposit', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balancetransfer',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('from_balance_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('to_balance_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='balancetransferstatus'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userlevel',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('unlocked_features', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('userlongterminvestment',
    sa.Column('allocation', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['longtermplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usermilestone',
    sa.Column('milestone_type', sa.Enum('FIRST_DEPOSIT', 'TRADING_VOLUME_100', 'TRADING_VOLUME_1000', 'CONSISTENT_PROFITS', 'PORTFOLIO_DIVERSIFICATION', 'ACCOUNT_AGE_30', 'ACCOUNT_AGE_90', 'REFERRAL_BONUS', name='milestonetype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('reward', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # --- FIX: Commented this out because the column already exists ---
    # op.add_column('user', sa.Column('long_term_balance', sa.Float(), nullable=False))
    # -----------------------------------------------------------------


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'long_term_balance')
    op.drop_table('usermilestone')
    op.drop_table('userlongterminvestment')
    op.drop_table('userlevel')
    op.drop_table('balancetransfer')
    op.drop_table('longtermplan')
    op.drop_table('levelrequirement')
    # ### end Alembic commands ###