"""fix_kyc_verification_system

Revision ID: 6113d7b9099f
Revises: 343d91d0c2f1
Create Date: 2025-09-27 21:03:47.573013

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6113d7b9099f'
down_revision = '343d91d0c2f1'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    
    # Create enums first
    risk_tolerance_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktolerance')
    risk_tolerance_enum.create(bind, checkfirst=True)
    
    trade_side_enum = sa.Enum('BUY', 'SELL', name='tradeside')
    trade_side_enum.create(bind, checkfirst=True)
    
    trade_status_enum = sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='tradestatus')
    trade_status_enum.create(bind, checkfirst=True)
    
    copy_status_enum = sa.Enum('ACTIVE', 'PAUSED', 'STOPPED', name='copystatus')
    copy_status_enum.create(bind, checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kycdocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('PASSPORT', 'DRIVERS_LICENSE', 'NATIONAL_ID', 'PROOF_OF_ADDRESS', name='kycdocumenttype', create_type=False), nullable=False),
    sa.Column('front_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('back_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofile',
    sa.Column('legal_first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('legal_last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('address_line_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tax_id_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('source_of_funds', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('risk_assessment_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # Add KYC columns first (these should work without issues)
    op.add_column('user', sa.Column('kyc_submitted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('kyc_approved_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('kyc_rejected_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # For enum conversions, we need to handle them carefully
    # First, let's try to apply the KYC-related changes only
    # The enum conversions can be handled separately if needed
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usertradercopy', 'copy_status',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'STOPPED', name='copystatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('user', 'kyc_rejected_reason')
    op.drop_column('user', 'kyc_approved_at')
    op.drop_column('user', 'kyc_submitted_at')
    op.alter_column('tradertrade', 'status',
               existing_type=sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='tradestatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('tradertrade', 'side',
               existing_type=sa.Enum('BUY', 'SELL', name='tradeside'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.alter_column('traderprofile', 'risk_tolerance',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktolerance'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_table('userprofile')
    op.drop_table('kycdocument')
    # ### end Alembic commands ###
