"""add_support_chat_tables

Revision ID: 7e3802458d80
Revises: 20251220_kyc_submitted_notif
Create Date: 2025-12-02 21:07:40.448314

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e3802458d80'
down_revision = '20251220_kyc_submitted_notif'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supportattachment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportattachment_created_at'), 'supportattachment', ['created_at'], unique=False)
    op.create_index(op.f('ix_supportattachment_user_id'), 'supportattachment', ['user_id'], unique=False)
    op.create_table('supportthread',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportthread_created_at'), 'supportthread', ['created_at'], unique=False)
    op.create_index(op.f('ix_supportthread_user_id'), 'supportthread', ['user_id'], unique=False)
    op.create_table('supportthreaditem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['supportthread.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportthreaditem_created_at'), 'supportthreaditem', ['created_at'], unique=False)
    op.create_index(op.f('ix_supportthreaditem_thread_id'), 'supportthreaditem', ['thread_id'], unique=False)
    op.create_index(op.f('ix_supportthreaditem_user_id'), 'supportthreaditem', ['user_id'], unique=False)
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('longtermplan', 'maximum_deposit',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_longtermplan_maximum_deposit', table_name='longtermplan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_longtermplan_maximum_deposit', 'longtermplan', ['maximum_deposit'], unique=False)
    op.alter_column('longtermplan', 'maximum_deposit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_supportthreaditem_user_id'), table_name='supportthreaditem')
    op.drop_index(op.f('ix_supportthreaditem_thread_id'), table_name='supportthreaditem')
    op.drop_index(op.f('ix_supportthreaditem_created_at'), table_name='supportthreaditem')
    op.drop_table('supportthreaditem')
    op.drop_index(op.f('ix_supportthread_user_id'), table_name='supportthread')
    op.drop_index(op.f('ix_supportthread_created_at'), table_name='supportthread')
    op.drop_table('supportthread')
    op.drop_index(op.f('ix_supportattachment_user_id'), table_name='supportattachment')
    op.drop_index(op.f('ix_supportattachment_created_at'), table_name='supportattachment')
    op.drop_table('supportattachment')
    # ### end Alembic commands ###
