"""Add trader profiles, user trader copies, and trader trades

Revision ID: 9f1440037223
Revises: 26ae61361ef8
Create Date: 2025-09-26 13:51:45.435117

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9f1440037223'
down_revision = '26ae61361ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create tables using existing enum types
    op.create_table('traderprofile',
    sa.Column('trading_strategy', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('risk_tolerance', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('copy_fee_percentage', sa.Float(), nullable=False),
    sa.Column('minimum_copy_amount', sa.Float(), nullable=False),
    sa.Column('total_copiers', sa.Integer(), nullable=False),
    sa.Column('total_assets_under_copy', sa.Float(), nullable=False),
    sa.Column('average_monthly_return', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tradertrade',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('is_copyable', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trader_profile_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['trader_profile_id'], ['traderprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertradercopy',
    sa.Column('copy_amount', sa.Float(), nullable=False),
    sa.Column('copy_started_at', sa.DateTime(), nullable=False),
    sa.Column('copy_status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('copy_settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trader_profile_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['trader_profile_id'], ['traderprofile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertradercopy')
    op.drop_table('tradertrade')
    op.drop_table('traderprofile')
    # ### end Alembic commands ###
