"""add_roi_transaction_type

Revision ID: a9f9678b20b9
Revises: 078c1bc167c3
Create Date: 2025-10-15 02:40:24.452480

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a9f9678b20b9'
down_revision = '078c1bc167c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    longtermplantier_enum = postgresql.ENUM(
        'FOUNDATION', 'GROWTH', 'ELITE',
        name='longtermplantier'
    )
    longtermplantier_enum.create(op.get_bind())
    
    balancetransferstatus_enum = postgresql.ENUM(
        'PENDING', 'COMPLETED', 'FAILED', 'CANCELLED',
        name='balancetransferstatus'
    )
    balancetransferstatus_enum.create(op.get_bind())
    
    copystatus_enum = postgresql.ENUM(
        'ACTIVE', 'PAUSED', 'STOPPED',
        name='copystatus'
    )
    copystatus_enum.create(op.get_bind())
    
    milestonetype_enum = postgresql.ENUM(
        'FIRST_DEPOSIT', 'TRADING_VOLUME_100', 'TRADING_VOLUME_1000', 'CONSISTENT_PROFITS', 
        'PORTFOLIO_DIVERSIFICATION', 'ACCOUNT_AGE_30', 'ACCOUNT_AGE_90', 'REFERRAL_BONUS',
        name='milestonetype'
    )
    milestonetype_enum.create(op.get_bind())
    
    op.create_table('levelrequirement',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('longtermplan',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tier', postgresql.ENUM(name='longtermplantier', create_type=False), nullable=True),
    sa.Column('minimum_deposit', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balancetransfer',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('from_balance_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('to_balance_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', postgresql.ENUM(name='balancetransferstatus', create_type=False), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userlevel',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('unlocked_features', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('userlongterminvestment',
    sa.Column('allocation', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM(name='copystatus', create_type=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['longtermplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usermilestone',
    sa.Column('milestone_type', postgresql.ENUM(name='milestonetype', create_type=False), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('reward', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usermilestone')
    op.drop_table('userlongterminvestment')
    op.drop_table('userlevel')
    op.drop_table('balancetransfer')
    op.drop_table('longtermplan')
    op.drop_table('levelrequirement')
    
    # Drop enum types
    longtermplantier_enum = postgresql.ENUM(
        'FOUNDATION', 'GROWTH', 'ELITE',
        name='longtermplantier'
    )
    longtermplantier_enum.drop(op.get_bind())
    
    balancetransferstatus_enum = postgresql.ENUM(
        'PENDING', 'COMPLETED', 'FAILED', 'CANCELLED',
        name='balancetransferstatus'
    )
    balancetransferstatus_enum.drop(op.get_bind())
    
    copystatus_enum = postgresql.ENUM(
        'ACTIVE', 'PAUSED', 'STOPPED',
        name='copystatus'
    )
    copystatus_enum.drop(op.get_bind())
    
    milestonetype_enum = postgresql.ENUM(
        'FIRST_DEPOSIT', 'TRADING_VOLUME_100', 'TRADING_VOLUME_1000', 'CONSISTENT_PROFITS', 
        'PORTFOLIO_DIVERSIFICATION', 'ACCOUNT_AGE_30', 'ACCOUNT_AGE_90', 'REFERRAL_BONUS',
        name='milestonetype'
    )
    milestonetype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
