"""Add execution events table for simulation auditing

Revision ID: ba9360c196d5
Revises: ab41ef5a2689
Create Date: 2025-09-28 02:29:06.605100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba9360c196d5'
down_revision = 'ab41ef5a2689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The executioneventtype enum already exists, so we just create the table
    op.create_table('executionevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('TRADER_SIMULATION', 'FOLLOWER_PROFIT', 'MANUAL_ADJUSTMENT', name='executioneventtype', create_type=False), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('trader_profile_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trader_profile_id'], ['traderprofile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('traderprofile', 'risk_tolerance',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktolerance'),
               existing_nullable=False,
               postgresql_using='risk_tolerance::risktolerance')
    op.alter_column('tradertrade', 'side',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('BUY', 'SELL', name='tradeside'),
               existing_nullable=False,
               postgresql_using='side::tradeside')
    op.alter_column('tradertrade', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='tradestatus'),
               existing_nullable=False,
               postgresql_using='status::tradestatus')
    op.alter_column('usertradercopy', 'copy_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('ACTIVE', 'PAUSED', 'STOPPED', name='copystatus'),
               existing_nullable=False,
               postgresql_using='copy_status::copystatus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usertradercopy', 'copy_status',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'STOPPED', name='copystatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('tradertrade', 'status',
               existing_type=sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='tradestatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('tradertrade', 'side',
               existing_type=sa.Enum('BUY', 'SELL', name='tradeside'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.alter_column('traderprofile', 'risk_tolerance',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktolerance'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_table('executionevent')
    # ### end Alembic commands ###
